### ISSUE TITLE
Invalid argument for foreach

### ISSUE THREAD

**Issue by z-h-z-h** [MacsiDigital/laravel-zoom#25]
The error only occurs when host_video and participant_video both set to false

```
Invalid argument supplied for foreach() {"exception":"[object] (ErrorException(code: 0): Invalid argument supplied for foreach() at /var
/www/www.tazman.co.il/vendor/macsidigital/laravel-zoom/src/Support/Model.php:252)
[stacktrace]
#0 /var/www/www.tazman.co.il/vendor/macsidigital/laravel-zoom/src/Support/Model.php(252): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(2, 'Invalid argu
men...', '/var/www/www.ta...', 252, Array)
#1 /var/www/www.tazman.co.il/vendor/macsidigital/laravel-zoom/src/Support/Model.php(158): MacsiDigital\\Zoom\\Support\\Model->fill(false)
#2 /var/www/www.tazman.co.il/vendor/macsidigital/laravel-zoom/src/Support/Model.php(209): MacsiDigital\\Zoom\\Support\\Model->setAttribute('settings', Array)
#3 /var/www/www.tazman.co.il/vendor/macsidigital/laravel-zoom/src/Support/Model.php(253): MacsiDigital\\Zoom\\Support\\Model->__set('settings', Array)
#4 /var/www/www.tazman.co.il/vendor/macsidigital/laravel-zoom/src/Meeting.php(106): MacsiDigital\\Zoom\\Support\\Model->fill(Array)
#5 /var/www/www.tazman.co.il/vendor/macsidigital/laravel-zoom/src/Support/Model.php(244): MacsiDigital\\Zoom\\Meeting->make(Array)
#6 /var/www/www.tazman.co.il/app/Services/Zoom/ZoomMeetingsService.php(38): MacsiDigital\\Zoom\\Support\\Model->create(Array)
#7 /var/www/www.tazman.co.il/app/Services/Zoom/ZoomMeetingsService.php(55): App\\Services\\Zoom\\ZoomMeetingsService->create(Object(App\\Models\\CourseMeetingDescription),
 Object(App\\Models\\Zoom), Object(Illuminate\\Support\\Carbon))

```
Parameters for meeting creation
```
[
     "topic" => "test #2",
     "type" => 2,
     "start_time" => "2020-04-07T16:31:22",
     "timezone" => "Asia/Jerusalem",
     "password" => "12345678",
     "settings" => [
       "host_video" => false,
       "participant_video" => false,
       "join_before_host" => false,
       "mute_upon_entry" => false,
       "waiting_room" => false,
       "meeting_authentication" => false,
       "audio" => "voip",
       "auto_recording" => "none",
       "global_dial_in_countries" => [
         "IL",
         "Israel",
       ],
       "use_pmi" => false,
     ],
   ]
```

And how I used it

```
$zoomService = new Zoom();
$zoomUser = $zoomService->user->first();
$zoomMeeting = $zoomUser->meetings()->create($params);
```

**Comment by colinhall17** [comment]
Hi all

Apologies in the delay in coming back to you, when I created this package it was a quick build for a project I needed it for and I made it open source in case it would help someone. 

With the increased use of Zoom around the world its gaining some traction, so I've built 3 new versions for Laravel 5.5 upwards, make sure you select the correct version for your version of Laravel.

We now handle settings a lot better, check out the documentation for how to use.

Open a new issue with any problems.
